# This is the configuration used to check the rubocop source code.
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*.rb'
    - 'tmp/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

