sudo: true
language: ruby
rvm:
  - 2.5.0
before_install:
  - sudo gem install bundler -v 1.16.1
  - sudo bundle install
  - curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash
  - sudo ./install_keys.sh

script: sudo bundle exec rake
