sudo: false
language: ruby
rvm:
  - 2.5.0
before_install:
  - gem install bundler -v 1.16.1
  - curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash
  - ./install_keys.sh
